# This is a basic workflow to help you get started with Actions

name: Activity Types a

# Controls when the workflow will run
on:
  pull_request: 
    types: [ "synchronize" ]
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo Running whenever a PR is opened or synchronized AND base branch is main
