# This is a basic workflow to help you get started with Actions

name: Using Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    # Default config for all steps
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Printing folders
        run: ls
        # Diretorio onde a acao irá acontecer
        working-directory: ./
